version: '3'

services:
  db_mysql:
    container_name: mysql_database
    image: mysql:8.0.32
    restart: always
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=123456
    ports:
      - "3306:3306"